name: SQL Code Convention Check

on:
  workflow_dispatch:

jobs:
  sql_linting:
    name: Перевірка SQL-схеми на відповідність нормам
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Встановити SQLFluff
        run: pip install sqlfluff

      - name: Перевірити DataSchema.sql
        run: sqlfluff lint DataSchema.sql --dialect=postgres
