name: C# Code Convention Check

on:
  workflow_dispatch:

jobs:
  csharp_linting:
    name: Перевірка C#-модуля на відповідність нормам
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Встановити .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # або іншу версію твого проєкту

      - name: Встановити dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Додати dotnet tools у PATH
        run: echo "/home/runner/.dotnet/tools" >> $GITHUB_PATH

      - name: Перевірити стиль коду
        run: |
          dotnet format RelaxationSystem.csproj --check --verbosity diagnostic
