name: C# Code Convention Check

on:
  workflow_dispatch:

jobs:
  csharp_linting:
    name: Перевірка C#-модуля на відповідність нормам
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Встановити dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Перевірити ProgramCode.cs
        run: dotnet-format --verify-no-changes --folder .
