name: C# Code Convention Check

on:
  workflow_dispatch:

jobs:
  csharp_linting:
    name: Перевірка C#-модуля на відповідність нормам
    runs-on: ubuntu-latest

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v3

      - name: Встановлення .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Встановлення dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Перевірка стилю коду
        run: dotnet format --verify-no-changes --verbosity diagnostic
